### ISSUE TITLE
Can't reconnect with Maiar App after disconnecting with Maiar App

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#91]
In order to reconnect with Maiar App after a disconnection, one needs to refresh the page and close and reopen Maiar.

**Comment by newbreedofgeek** [comment]
@damienen pls repro with some details.

This may be related to #93

**Comment by damienen** [comment]
Solved with https://github.com/Itheum/data-dex/commit/cea6cbd81614787b4521bb09770ecf02dfb87461

**Comment by newbreedofgeek** [comment]
Not solved... logic does not work on browser plugin, maiar wallet etc
